all:
	latex visualization
	bibtex visualization
	latex visualization
	latex visualization
pdf:
	pdflatex visualization
	bibtex visualization
	pdflatex visualization
	pdflatex visualization
view: all
	okular visualization.dvi
viewpdf: all
	evince visualization.pdf
clean:
	rm *.aux *.bbl *.blg *.log *.backup *.toc